In [132]:
import pandas as pd
import numpy as np

df=pd.read_excel("HDR21-22_Statistical_Annex_HDI_Trends_Table.xlsx")

df.head(10)

HDI rank                 Country   1990 Unnamed: 3   2000  Unnamed: 5  \
0       1.0             Switzerland  0.851        NaN  0.887         NaN   
1       2.0                  Norway  0.838        NaN  0.913         NaN   
2       3.0                 Iceland  0.811        NaN  0.871         NaN   
3       4.0  Hong Kong, China (SAR)  0.788        NaN  0.851         NaN   
4       5.0               Australia  0.865        NaN  0.896         NaN   
5       6.0                 Denmark  0.834        NaN  0.889         NaN   
6       7.0                  Sweden   0.81        NaN  0.904         NaN   
7       8.0                 Ireland  0.737        NaN  0.847         NaN   
8       9.0                 Germany  0.829        NaN  0.889         NaN   
9      10.0             Netherlands  0.847        NaN  0.893         NaN   

    2010  Unnamed: 7   2015  Unnamed: 9  ... Unnamed: 17  2015-2021   a  \
0  0.942         NaN  0.954         NaN  ...         NaN          0 NaN   
1  0.941         NaN  0.953         NaN  ...         NaN          0 NaN   
2  0.902         NaN  0.945         NaN  ...         NaN          0 NaN   
3  0.907         NaN  0.935         NaN  ...         NaN          3 NaN   
4  0.923         NaN  0.933         NaN  ...         NaN          3 NaN   
5  0.913         NaN  0.936         NaN  ...         NaN          0 NaN   
6   0.91         NaN  0.937         NaN  ...         NaN         -2 NaN   
7  0.904         NaN  0.925         NaN  ...         NaN          6 NaN   
8  0.926         NaN  0.938         NaN  ...         NaN         -5 NaN   
9  0.917         NaN  0.932         NaN  ...         NaN         -1 NaN   

   1990-2000 Unnamed: 21  2000-2010 Unnamed: 23  2010-2021 Unnamed: 25  \
0   0.415188         NaN   0.603416         NaN   0.191175         NaN   
1   0.860862         NaN   0.302529         NaN   0.191376         NaN   
2   0.716292         NaN   0.350338         NaN   0.558614         NaN   
3   0.772106         NaN   0.639338         NaN   0.441176         NaN   
4    0.35273         NaN   0.297329         NaN    0.27205         NaN   
5   0.640682         NaN   0.266742         NaN   0.342573         NaN   
6   1.104001         NaN   0.066174         NaN   0.362971         NaN   
7   1.400849         NaN   0.653412         NaN   0.404047         NaN   
8   0.701218         NaN   0.408603         NaN   0.155858         NaN   
9    0.53026         NaN   0.265561         NaN   0.235146         NaN   

   1990-2021  
0   0.396274  
1   0.442772  
2   0.542184  
3   0.611757  
4   0.306225  
5   0.414149  
6   0.505353  
7    0.80515  
8   0.413061  
9   0.340069  

[10 rows x 27 columns]

## **GOODNESS OF FIT TEST**

In [133]:
arr=[]
num_rows = 196
df = df.iloc[:num_rows]
for index, row in df.iterrows():
    country = row['Country']
    for col in df.columns[2:17]:
        if(pd.notnull(row[col])):
            entry = [country, col, row[col]]  # Creating an array with row_name, column_name, and value
            arr.append(entry)  # Appending the array to the list

arr_2d = np.array(arr)

# Printing the resulting 2D array
for i in range(100):
    print(arr_2d[i])

['Switzerland' '1990' '0.851']
['Switzerland' '2000' '0.887']
['Switzerland' '2010' '0.942']
['Switzerland' '2015' '0.954']
['Switzerland' '2018' '0.959']
['Switzerland' '2019' '0.962']
['Switzerland' '2020' '0.956']
['Switzerland' '2021' '0.962']
['Norway' '1990' '0.838']
['Norway' '2000' '0.913']
['Norway' '2010' '0.941']
['Norway' '2015' '0.953']
['Norway' '2018' '0.962']
['Norway' '2019' '0.961']
['Norway' '2020' '0.959']
['Norway' '2021' '0.961']
['Iceland' '1990' '0.811']
['Iceland' '2000' '0.871']
['Iceland' '2010' '0.902']
['Iceland' '2015' '0.945']
['Iceland' '2018' '0.959']
['Iceland' '2019' '0.96']
['Iceland' '2020' '0.957']
['Iceland' '2021' '0.959']
['Hong Kong, China (SAR)' '1990' '0.788']
['Hong Kong, China (SAR)' '2000' '0.851']
['Hong Kong, China (SAR)' '2010' '0.907']
['Hong Kong, China (SAR)' '2015' '0.935']
['Hong Kong, China (SAR)' '2018' '0.949']
['Hong Kong, China (SAR)' '2019' '0.952']
['Hong Kong, China (SAR)' '2020' '0.949']
['Hong Kong, China (SAR)' '2021' '0

In [134]:
import random

# Specifing the sample size
sample_size = 100

# Performing simple random sampling
sample = random.sample(arr_2d.tolist(), sample_size)

print("Simple Random Sample :", sample)


Simple Random Sample : [['Senegal', '2021', '0.511'], ['Mali', '2020', '0.427'], ['China', '2018', '0.755'], ['Mauritius', '2019', '0.817'], ['Niger', '2020', '0.401'], ['Bahamas', '1990', '..'], ['Cambodia', '2000', '0.425'], ['Slovenia', '2015', '0.903'], ['Australia', '1990', '0.865'], ['Lesotho', '1990', '0.479'], ['Madagascar', '2018', '0.507'], ['Montenegro', '1990', '..'], ['Morocco', '2010', '0.603'], ['Guatemala', '2000', '0.55'], ['Ecuador', '1990', '0.651'], ['Lithuania', '2021', '0.875'], ['Tajikistan', '2010', '0.636'], ['El Salvador', '1990', '0.525'], ['Denmark', '2010', '0.913'], ['Timor-Leste', '2021', '0.607'], ['Indonesia', '2020', '0.709'], ['Kyrgyzstan', '1990', '0.638'], ['Marshall Islands', '2021', '0.639'], ['Grenada', '2018', '0.797'], ['Nicaragua', '2020', '0.654'], ['Haiti', '2018', '0.541'], ['Suriname', '1990', '..'], ["Lao People's Democratic Republic", '2000', '0.47'], ['India', '1990', '0.434'], ['Spain', '2019', '0.908'], ['Micronesia (Federated States 

In [135]:
years={}
for i in sample:
  if i[1] not in years:
    years[i[1]]=1
  else:
    years[i[1]]+=1

print(years)



{'2021': 11, '2020': 19, '2018': 9, '2019': 11, '1990': 14, '2000': 18, '2015': 8, '2010': 10}


In [136]:
print(len(years))

8


## using the above years for the goodness of fit tests

In [137]:
expected_value=100/len(years)
print(round(expected_value))

12


In [138]:
chi_sq=0
for i in years:
  chi_sq+=((years[i]-expected_value)**2)/expected_value

print(chi_sq)

9.44


chi_square tabulated for number of degrees of freedom = 36-1 =35 at alpha = 5% is 14.067

In [139]:
chi_sq_tab=14.067

In [140]:
if chi_sq<=chi_sq_tab:
  print("Accept H0 , therefore it is good fit")
else:
  print("Reject Ho , Accept H1 . therefore not a good fit")

Accept H0 , therefore it is good fit


# **Chi-square test for independence**

In [156]:
import pandas as pd

# Specify the years and countries you are interested in
years_of_interest = [2019, 2020, 2021]
countries_of_interest = ['India', 'Germany', 'South Africa']

# Filter the DataFrame based on the specified years and countries
filtered_df = df[df['Country'].isin(countries_of_interest)][[
    'Country'] + years_of_interest]

# Print the header row with years and countries
print("Year", end='\t')
for country in countries_of_interest:
    print(f"\t{country}", end='')
print()
arr_3d=[]
# Print the data for the specified years and countries
for year in years_of_interest:
    print(year, end='\t')
    entry=[]
    for country in countries_of_interest:
        value = filtered_df[filtered_df['Country'] == country][year].values[0]
        entry.append(value)
        print(f"\t{value:.3f}", end='')
    arr_3d.append(entry)
    print()

Year		India	Germany	South Africa
2019		0.645	0.948	0.736
2020		0.642	0.944	0.727
2021		0.633	0.942	0.713


In [157]:
arr_3d

[[0.645, 0.948, 0.736], [0.642, 0.944, 0.727], [0.633, 0.942, 0.713]]

In [143]:
import pandas as pd
import numpy as np

# Create a 3 by 3 array to store the data
data_array = []

# Populate the array with the selected data and calculate row and column sums
for year in years_of_interest:
    row_data = []
    for country in countries_of_interest:
        value = filtered_df[filtered_df['Country'] == country][year].values[0]
        row_data.append(value)
    row_sum = sum(row_data)
    row_data.append(row_sum)  # Append row sum to the row
    data_array.append(row_data)

# Calculate column sums and append them as the last row
column_sums = np.sum(data_array, axis=0)
data_array.append(list(column_sums))

# Convert the nested list to a NumPy array
data_array = np.array(data_array)

# Calculate the e values based on the specified formula
e_array = np.zeros((3, 3))
for i in range(3):
    for j in range(3):
        e_array[i, j] = (data_array[i, -1] * data_array[-1, j]
                         ) / data_array[-1, -1]

# Print the arrays
print("Original Data Array:")
print(data_array)
print("\ne Array:")
print(e_array)

Original Data Array:
[[0.645 0.948 0.736 2.329]
 [0.642 0.944 0.727 2.313]
 [0.633 0.942 0.713 2.288]
 [1.92  2.834 2.176 6.93 ]]

e Array:
[[0.64526407 0.95243665 0.73129928]
 [0.64083117 0.94589351 0.72627532]
 [0.63390476 0.93566984 0.7184254 ]]


In [144]:
test_value=np.sum((np.array(data_array[:-1,:-1])-np.array(e_array))**2/np.array(e_array))
test_value

0.00014272483258223107

In [145]:
alpha=5
chi_sq_tab=9.488

if test_value<chi_sq_tab:
    print(r'accept H0')
else:
    print(r'reject H0 accept H1')

accept H0


# **Chi-square test for homogeneity**

In [146]:
country="India"
years=[2019,2020,2021]

arr=[[],[]]

country_data = df[df['Country'].notnull() & (df['Country'] == country)]

# Extracting values for the specified years
country_data = country_data[years].values.tolist()

print(country_data)

[[0.645, 0.642, 0.633]]


In [147]:
yes=np.array(country_data)
no=1-yes

no

array([[0.355, 0.358, 0.367]])

In [148]:
arr[0]=yes
arr[1]=no

arr

[array([[0.645, 0.642, 0.633]]), array([[0.355, 0.358, 0.367]])]

In [149]:
x1=np.sum(arr[0])
x2=np.sum(arr[1])
arr[0]= np.append(arr[0], x1)
arr[1]=np.append(arr[1], x2)
arr.append(np.array([1,1,1,3]))
arr

[array([0.645, 0.642, 0.633, 1.92 ]),
 array([0.355, 0.358, 0.367, 1.08 ]),
 array([1, 1, 1, 3])]

In [150]:
import numpy as np

e_array = np.zeros((3, 3)) 
data_array = np.array(arr)  

for i in range(3):
    for j in range(3):
        e_array[i, j] = (data_array[i, -1] * data_array[-1, j]) / data_array[-1, -1]

# Calculate row sums and append them to each respective row
row_sums = np.sum(e_array, axis=1)
e_array = np.column_stack((e_array, row_sums))

print(e_array)


[[0.64 0.64 0.64 1.92]
 [0.36 0.36 0.36 1.08]
 [1.   1.   1.   3.  ]]


In [155]:
test_value=np.sum(((data_array[:,:])-(e_array[:,:]))**2/(e_array))
test_value

0.0003385416666666672